/**
 * Regenerate `openapi.json` from the running application.
 *
 * The document is generated by booting the real Fastify app and asking it for
 * its Swagger schema, rather than maintained by hand. That is the only way the
 * published spec cannot drift from the schemas that actually validate requests
 * and serialize responses.
 *
 *   npm run openapi
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import { buildApp, API_VERSION } from '../src/app.js';
import { ProcessorRegistry, SandboxProcessor } from '../src/processors/index.js';
import type { Db } from '../src/db/index.js';

const OUT = resolve(process.cwd(), 'openapi.json');

/**
 * Boot must not need a database. If a future change adds a query at startup,
 * this Proxy throws instead of silently succeeding against an accidental
 * connection, and the spec stays generatable on a laptop with no Postgres.
 */
const noDatabase = new Proxy({} as Db, {
  get(_t, prop) {
    throw new Error(
      `OpenAPI generation touched db.${String(prop)}. Booting the app must not ` +
        `require a database; move the query behind a request hook.`,
    );
  },
});

const registry = new ProcessorRegistry();
registry.register(new SandboxProcessor());

const app = await buildApp({ db: noDatabase, registry, apiVersion: API_VERSION });

// `app.swagger()` returns a live reference, so serialize once and sort nothing:
// the key order comes from route registration, which is stable.
const document = app.swagger() as Record<string, unknown>;
const paths = Object.keys(document.paths as object).sort();

const { paths: _drop, ...rest } = document;
const sorted = {
  openapi: document.openapi,
  info: document.info,
  servers: document.servers,
  components: document.components,
  paths: Object.fromEntries(paths.map((p) => [p, (document.paths as Record<string, unknown>)[p]])),
  ...rest,
};

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, `${JSON.stringify(sorted, null, 2)}\n`, 'utf8');

await app.close();
console.log(`wrote ${relative(process.cwd(), OUT)} (${paths.length} paths, API ${API_VERSION})`);
for (const p of paths) console.log(`  ${p}`);